apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.11.1
  count: {{ .Values.kibana.replicas }}
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
           {{- toYaml .Values.kibana.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - ls /
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
  config:
    server:
      basePath: {{ .Values.kibana.frontendPrefix }}
      rewriteBasePath: true