apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wsh-java-webservice.fullname" . }}
  labels:
    {{- include "wsh-java-webservice.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wsh-java-webservice.selectorLabels" . | nindent 4 }}
  maxUnavailable: {{ .Values.maxUnavailable }}
