timezone: Europe/Berlin

image:
  registry: docker-registry.wirsindhandwerk.de
  repository: wsh/cli-tools
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

updateStrategy: RollingUpdate

restartPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.1
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: []

extraVolumeMounts: []

extraEnv: []
